### ISSUE TITLE
Header data, no stings

### ISSUE THREAD

**Issue by RobertMolenaar-UT** [SumeetRohilla/readPTU_FLIM#3]
I'm using this code to convert PTU data. I need some string data from the header. At the moment all string/text data is shown as a '8' I believe something goes wrong with the conversion of sting data. Does someone how fix or use the right sting conversion. UTF-8 or UTF-16.

Thanks in advance.

**Comment by SumeetRohilla** [comment]
Fixed. Thanks to the correction suggested by @RobertMolenaar-UT.
All the strings are correctly read from PTU file.
