### ISSUE TITLE
can't download example file

### ISSUE THREAD

**Issue by ChrisHal** [SumeetRohilla/readPTU_FLIM#4]
Hello, I tried to download the example file mentioned in README.md (Test_FLIM_image_daisyPollen_PicoHarp_2.ptu). It seems that the link is not working.

Regards,
Christian

**Comment by SumeetRohilla** [comment]
Hey Chris..

Apologies for the broken demo ptu file link. I have fixed it..Happy FLIMing!

Best, 
Sumeet

**Comment by ChrisHal** [comment]
Hey Sumeet,
thanks!

Best,
Christian


Am Do., 2. Sept. 2021 um 15:08 Uhr schrieb SumeetRohilla <
***@***.***>:
